// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get dashboard => 'Dashboard';

  @override
  String get plantLocation => 'Plant Location';

  @override
  String get allPlant => 'All Plant';

  @override
  String get inspectionProgress => 'Inspection Progress';

  @override
  String get complete => 'Complete';

  @override
  String get incomplete => 'Incomplete';

  @override
  String get completionRate => 'Completion Rate';

  @override
  String get issuesBySeverity => 'Issues By Severity';

  @override
  String get inspection => 'Inspection';

  @override
  String get analysisResult => 'Analysis Result';

  @override
  String get objectDetected => 'Object Detected';

  @override
  String get category => 'Category';

  @override
  String get gpsLocation => 'GPS Location';

  @override
  String get severity => 'Severity';

  @override
  String get description => 'Description';

  @override
  String get recommendation => 'Recommendation';

  @override
  String get manualOverride => 'Override AI Prediction?';

  @override
  String get submit => 'SUBMIT';

  @override
  String get camera => 'Camera';

  @override
  String get gallery => 'Gallery';

  @override
  String get searchDetail => 'Search by Detail';

  @override
  String get searchObject => 'Search by Object';

  @override
  String get advancedFilters => 'Advanced Filters';

  @override
  String get filterOptions => 'Filter Options';

  @override
  String get reset => 'Reset';

  @override
  String get status => 'Status';

  @override
  String get allCategories => 'All Categories';

  @override
  String get severityLevel => 'Severity Level';

  @override
  String get applyFilter => 'Apply Filter';

  @override
  String get safety => 'SAFETY';

  @override
  String get hygiene => 'HYGIENE';

  @override
  String get orderliness => 'ORDERLINESS';

  @override
  String get shift => 'Shift';

  @override
  String get resolve => 'Resolve';

  @override
  String get reports => 'Reports';

  @override
  String get listReports => 'List Reports';

  @override
  String get tasks => 'Tasks';

  @override
  String get completedTasks => 'Completed Tasks';

  @override
  String get employeeId => 'Employee ID';

  @override
  String get email => 'Email';

  @override
  String get department => 'Department';

  @override
  String get accountDetails => 'Account Details';

  @override
  String get assignedPlant => 'Assigned Plant';

  @override
  String get settings => 'Pengaturan';

  @override
  String get browseMenu => 'BROWSE MENU';

  @override
  String get accountSupport => 'ACCOUNT & SUPPORT';

  @override
  String get uploadToServer => 'Uploading to Server...';

  @override
  String get object => 'Object';

  @override
  String get editRecommendation => 'Edit recommendation...';

  @override
  String get submitChanges => 'SUBMIT CHANGES';

  @override
  String get cancel => 'Cancel';

  @override
  String get completeReport => 'COMPLETE REPORT';

  @override
  String get profile => 'Profile';

  @override
  String get language => 'Language';

  @override
  String get actionDescription => 'Action Description';

  @override
  String get editManual => 'Edit Manual';

  @override
  String get typeManualHint => 'Type manually...';

  @override
  String get aiAnalysisResultHint => 'AI analysis results...';

  @override
  String get submitCompletion => 'SUBMIT COMPLETION';

  @override
  String get editAiDescriptionTitle => 'Edit AI Description';

  @override
  String get editAiDescriptionDialog =>
      'Do you want to manually edit the description generated by the AI?';

  @override
  String get yesEdit => 'Yes, Edit';

  @override
  String get errorLoadCompletion => 'Failed to load completion';

  @override
  String get completionSummary => 'COMPLETION SUMMARY';

  @override
  String get actionNote => 'Action Note';

  @override
  String get resolvedBy => 'Resolved By';

  @override
  String get resolutionTime => 'Resolution Time';

  @override
  String get descriptionTitle => 'DESCRIPTION';

  @override
  String get editDescriptionHint => 'Edit description...';
}
